# Generated by Django 4.2.1 on 2024-08-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Google', 'Google'), ('Meta', 'Meta'), ('Groq', 'Groq'), ('Mistral AI', 'Mistral AI')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
